name: pluto_layout
description: PlutoLayout is a Flutter UI package that can configure a menu or tab screen on each side.
version: 1.0.0
homepage: https://pluto.weblaze.dev
repository: https://github.com/bosskmk/pluto_layout

environment:
  sdk: '>=3.0.0<4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  collection:
  rxdart:
  flutter_riverpod:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
